# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '書籍', 'verbose_name_plural': '書籍'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分類', 'verbose_name_plural': '分類'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '標籤', 'verbose_name_plural': '標籤'},
        ),
    ]
